DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USERS CASCADE;
DROP  TABLE IF EXISTS MEALS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ CASCADE ;

CREATE SEQUENCE GLOBAL_SEQ START 100000;

CREATE TABLE USERS
(
  id         INTEGER PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  name       VARCHAR,
  email      VARCHAR NOT NULL,
  password   VARCHAR NOT NULL,
  registered TIMESTAMP DEFAULT now(),
  enabled    BOOL DEFAULT TRUE
);
CREATE UNIQUE INDEX unique_email ON USERS (email);

CREATE TABLE USER_ROLES
(
  user_id INTEGER NOT NULL,
  role    VARCHAR,
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE MEALS
(
  id INTEGER  PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  description VARCHAR,
  calories INTEGER not null ,
  dateTime TIMESTAMP default now(),
  user_by_id INTEGER not null,
  CONSTRAINT id UNIQUE (id),
  FOREIGN KEY (user_by_id)REFERENCES users(id) ON DELETE CASCADE


);
